branch-defaults:
  default:
    environment: HCMEventDeveloperUtil
environment-defaults:
  AtomfeedBackendEnvironment:
    branch: null
    repository: null
global:
  application_name: AtomfeedBackend
  default_ec2_keyname: aws-eb
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
