name: Deploy to Elastic Beanstalk on dev push

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'
      - '!backend/**/*.md'
      - '!backend/**/*.MD'
      - '!backend/docs/**'
      - '!backend/**/*.txt'
      - '!backend/.gitignore'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Change directory to /backend
        run: cd backend

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Install AWS EB CLI
        run: |
          pip install --upgrade pip
          pip install awsebcli
        working-directory: ./backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to Elastic Beanstalk
        run: |
          git_hash=$(git rev-parse --short HEAD)
          eb deploy --message "Deploy from GitHub Actions - $git_hash" --label "gha-${git_hash}"
        working-directory: ./backend
